apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: registry
spec:
  rules:
  - host: registry.k8s.mylab.local
    http:
      paths:
      - backend:
          serviceName: registry-docker-registry
          servicePort: 5000
